repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v0.7.1
    hooks:
      -   id: check-merge-conflict
      -   id: check-yaml
      -   id: end-of-file-fixer
      -   id: trailing-whitespace
      -   id: check-added-large-files
      -   id: check-json
      -   id: detect-private-key
# Golang Hooks
  - repo: https://github.com/Bahjat/pre-commit-golang
    rev: v1.0.1
    hooks:
      - id: go-fmt-import
      - id: go-vet
      #- id: go-unit-tests

# JavaScript Hooks

# Docker hooks
  - repo: https://github.com/AleksaC/hadolint-py
    rev: v1.19.0
    hooks:
      - id: hadolint
        args: [--ignore, DL3025, --ignore, DL3018]
